# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\imis_Final\imis2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_testTab(object):
    def setupUi(self, testTab):
        testTab.setObjectName("testTab")
        testTab.resize(660, 545)
        self.central = QtWidgets.QWidget(testTab)
        self.central.setObjectName("central")
        self.tabWidget = QtWidgets.QTabWidget(self.central)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 641, 521))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tab.setObjectName("tab")
        self.pic1 = QtWidgets.QLabel(self.tab)
        self.pic1.setEnabled(True)
        self.pic1.setGeometry(QtCore.QRect(0, -20, 641, 521))
        self.pic1.setText("")
        self.pic1.setPixmap(QtGui.QPixmap("C:/Users/don99/Desktop/PythonWorkSpace/정보통신수요인원.png"))
        self.pic1.setObjectName("pic1")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pic2 = QtWidgets.QLabel(self.tab_2)
        self.pic2.setGeometry(QtCore.QRect(0, -30, 641, 521))
        self.pic2.setText("")
        self.pic2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
        self.pic2.setObjectName("pic2")
        self.cb1 = QtWidgets.QComboBox(self.tab_2)
        self.cb1.setGeometry(QtCore.QRect(500, 10, 131, 22))
        self.cb1.setEditable(False)
        self.cb1.setObjectName("cb1")
        self.cb1.addItem("")
        self.cb1.addItem("")
        self.cb1.addItem("")
        self.cb1.addItem("")
        self.cb1.addItem("")
        self.cb1.addItem("")
        self.cb1.addItem("")
        self.tabWidget.addTab(self.tab_2, "")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.pic3 = QtWidgets.QLabel(self.widget)
        self.pic3.setGeometry(QtCore.QRect(0, -30, 641, 521))
        self.pic3.setText("")
        self.pic3.setObjectName("pic3")
        self.cb2 = QtWidgets.QComboBox(self.widget)
        self.cb2.setGeometry(QtCore.QRect(510, 10, 121, 21))
        self.cb2.setObjectName("cb2")
        self.cb2.addItem("")
        self.cb2.addItem("")
        self.cb2.addItem("")
        self.cb2.addItem("")
        self.tabWidget.addTab(self.widget, "")
        self.btn1 = QtWidgets.QPushButton(self.central)
        self.btn1.setGeometry(QtCore.QRect(240, 290, 181, 81))
        self.btn1.setObjectName("btn1")
        testTab.setCentralWidget(self.central)

        self.retranslateUi(testTab)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(testTab)

    def retranslateUi(self, testTab):
        _translate = QtCore.QCoreApplication.translate
        testTab.setWindowTitle(_translate("testTab", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("testTab", "연도별 IT계열 수요 인원"))
        self.cb1.setItemText(0, _translate("testTab", "전체"))
        self.cb1.setItemText(1, _translate("testTab", "클라우드"))
        self.cb1.setItemText(2, _translate("testTab", "빅데이터"))
        self.cb1.setItemText(3, _translate("testTab", "IoT"))
        self.cb1.setItemText(4, _translate("testTab", "인공지능"))
        self.cb1.setItemText(5, _translate("testTab", "VR/AR/MR"))
        self.cb1.setItemText(6, _translate("testTab", "블록체인"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("testTab", "연도별 IT계열 세부직종 구인현황"))
        self.cb2.setItemText(0, _translate("testTab", "서울"))
        self.cb2.setItemText(1, _translate("testTab", "경기"))
        self.cb2.setItemText(2, _translate("testTab", "인천"))
        self.cb2.setItemText(3, _translate("testTab", "부산"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("testTab", "11월 지역별 구인현황"))
        self.btn1.setText(_translate("testTab", "시작하기"))
